### ISSUE TITLE
kubectl EXEC does not work

### ISSUE THREAD

**Issue by nacifyas** [Angatar/kubectl#2]
I would like to know if there is any way to make the exec verb to work.
It seems like image lacks any kind of sh or bash, so running kubectl exec fails with the error:
```
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "725c3f2027059a129b3e1230ba048fd6cf9d77d371537cf0e95ec115c7825c45": OCI runtime exec failed: exec failed: unable to start container process: exec: "runuser -u www-data -- php -f /var/www/html/cron.php": stat runuser -u www-data -- php -f /var/www/html/cron.php: no such file or directory: unknown
```

Here is my manifest:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: nextcloud
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name:  kubeconfig
            configMap:
              name: kubeconfig
          containers:
          - name: nextcloud-cron
            image: d3fk/kubectl:latest
            args: ["exec", "deploy/nextcloud","-n" ,"nextcloud", "--","runuser -u www-data -- php -f /var/www/html/cron.php"]
            # args: ["get", "pods", "-l", "app=nextcloud", "-o", "custom-columns=:metadata.name", "-n", "nextcloud"]
            volumeMounts:
            - name:  kubeconfig
              mountPath: ./kube/config
              subPath: config
          restartPolicy: OnFailure
```
